//! Native adapter from heterogeneous GSS source gates to the canonical
//! `nonlinear291` E-encoding gadgets. The shared 193 topology is compiled only
//! for historical callers with `legacy-tools`.
//!
//! Each logical value is represented by two five-wire blocks with
//! `E(x) = x0 ^ x1 ^ maj(x2, x3, x4)`.  The public low wires are deliberately
//! kept separate from those carriers: the ingress derives balanced carrier
//! masks from a stable raw-data prefix and solves share-one lane zero so the
//! two blocks still decode to the raw logical bit.  The egress uses a clean
//! delta wire to replace the raw bit by the final two-share decode.
//! Consequently the returned circuit implements the source only on the
//! documented zero slice (every nondata input wire zero), exactly like the
//! other GSS gadgetizers.
//!
//! The per-operation gate bodies are compile-time canonical `mpmct1`
//! templates generated by the Python reference package.  The complete
//! `nonlinear291` adapter output, including its decomposed slice-zero preblock,
//! has physical fan-in at most two.  Later mixing stages have their own gate
//! vocabulary and are not covered by that statement.

use super::slice_guards::{
    SLICE_ZERO_CCNOT_GATES_PER_WIRE, try_nonlinear_slice_zero_preblock_dims,
};
use crate::circuit::Circuit as CnotCircuit;
use crate::circuit::xgate::{Lits, XGate, sort_lits};
use rand::Rng;
use std::sync::OnceLock;

#[cfg(feature = "legacy-tools")]
const TEMPLATE_193_R57: &str =
    include_str!("../../../security_tests/gadgetization/templates/nonlinear193_r57.mpmct1");
#[cfg(feature = "legacy-tools")]
const TEMPLATE_193_NAB: &str =
    include_str!("../../../security_tests/gadgetization/templates/nonlinear193_nab.mpmct1");
#[cfg(feature = "legacy-tools")]
const TEMPLATE_193_AND: &str =
    include_str!("../../../security_tests/gadgetization/templates/nonlinear193_and.mpmct1");
#[cfg(feature = "legacy-tools")]
const TEMPLATE_193_COPY: &str =
    include_str!("../../../security_tests/gadgetization/templates/nonlinear193_copy.mpmct1");
const TEMPLATE_291_R57: &str = include_str!("templates/nonlinear291_r57.mpmct1");
const TEMPLATE_291_NAB: &str = include_str!("templates/nonlinear291_nab.mpmct1");
const TEMPLATE_291_AND: &str = include_str!("templates/nonlinear291_and.mpmct1");
const TEMPLATE_291_COPY: &str = include_str!("templates/nonlinear291_copy.mpmct1");

const INGRESS_GATES_PER_LOGICAL: usize = 28;
const INGRESS_GATES_PER_SOURCE_GATE: usize = 18;
const EGRESS_GATES_PER_LOGICAL: usize = 12;
const NONLINEAR_SHUFFLE_PASSES: usize = 8;
// The managed GSS path requests ten probes per slice wire. Keep a finite API
// boundary for direct callers so a hostile `slice_gate_count` cannot turn a
// small, otherwise valid layout into an unbounded allocation request.
const MAX_SLICE_GATES_PER_NONDATA_WIRE: usize = 64;

/// Canonical nonlinear E-gadget body selected for each source operation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NonlinearGssMode {
    #[cfg(feature = "legacy-tools")]
    Nonlinear193,
    Nonlinear291,
}

impl NonlinearGssMode {
    fn shared_ancillas(self) -> usize {
        match self {
            #[cfg(feature = "legacy-tools")]
            NonlinearGssMode::Nonlinear193 => 0,
            // Two fallback, 24 persistent-prefix, and one temporary wire.
            NonlinearGssMode::Nonlinear291 => 27,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum TemplateOp {
    R57,
    Nab,
    And,
    Copy,
}

impl TemplateOp {
    fn name(self) -> &'static str {
        match self {
            TemplateOp::R57 => "r57",
            TemplateOp::Nab => "nab",
            TemplateOp::And => "and",
            TemplateOp::Copy => "copy",
        }
    }

    fn has_a(self) -> bool {
        self != TemplateOp::Copy
    }
}

#[derive(Clone, Debug)]
struct TemplateGate {
    target: usize,
    comp: bool,
    ctrls: Vec<(usize, bool)>,
}

#[derive(Clone, Debug)]
struct Template {
    num_wires: usize,
    gates: Vec<TemplateGate>,
}

#[derive(Clone, Copy, Debug)]
struct SourceOp {
    kind: TemplateOp,
    target: usize,
    a: Option<usize>,
    b: usize,
}

#[derive(Clone, Copy, Debug)]
struct EncodedValue {
    share1: [u16; 5],
    share2: [u16; 5],
}

#[derive(Clone, Copy, Debug)]
struct GateWires {
    fresh: [u16; 5],
    output: [u16; 3],
    chaff: [u16; 4],
}

#[derive(Clone, Debug)]
struct SharedWires {
    scratch: u16,
    scratch2: u16,
    decomp: Option<[u16; 2]>,
    persistent: Option<[u16; 24]>,
    temporary: Option<u16>,
}

#[derive(Clone, Debug)]
struct PhysicalLayout {
    values: Vec<EncodedValue>,
    gate_wires: Vec<GateWires>,
    shared: SharedWires,
    deltas: Vec<u16>,
    total: usize,
}

/// Return the exact physical wire count required by the canonical adapter.
///
/// This planner performs checked arithmetic and enforces the repository's
/// `u16` XGate ceiling. Callers may use it before sampling or writing source
/// artifacts; construction uses the same function, so preflight cannot drift
/// from the actual layout.
pub fn nonlinear_gss_wire_count(
    logical_n: usize,
    gate_count: usize,
    mode: NonlinearGssMode,
) -> Result<usize, String> {
    // raw n + E carriers 10n + output deltas n + per-gate 12 + shared 2/29.
    let logical = logical_n
        .checked_mul(12)
        .ok_or_else(|| "nonlinear GSS wire-count overflow in 12*logical_n".to_string())?;
    let per_gate = gate_count
        .checked_mul(12)
        .ok_or_else(|| "nonlinear GSS wire-count overflow in 12*gate_count".to_string())?;
    let total = logical
        .checked_add(per_gate)
        .and_then(|value| value.checked_add(2 + mode.shared_ancillas()))
        .ok_or_else(|| "nonlinear GSS total wire-count overflow".to_string())?;
    if total > u16::MAX as usize {
        return Err(format!(
            "nonlinear GSS adapter needs {total} wires for logical_n={logical_n}, \
             gates={gate_count}, mode={mode:?}; the XGate capacity is {}",
            u16::MAX
        ));
    }
    Ok(total)
}

fn take_array<const N: usize>(cursor: &mut usize) -> [u16; N] {
    let start = *cursor;
    *cursor += N;
    std::array::from_fn(|offset| (start + offset) as u16)
}

fn build_layout(
    logical_n: usize,
    gate_count: usize,
    mode: NonlinearGssMode,
) -> Result<PhysicalLayout, String> {
    let total = nonlinear_gss_wire_count(logical_n, gate_count, mode)?;
    // 0..logical_n are the stable raw public wires.
    let mut cursor = logical_n;
    let values = (0..logical_n)
        .map(|_| EncodedValue {
            share1: take_array(&mut cursor),
            share2: take_array(&mut cursor),
        })
        .collect();
    let gate_wires = (0..gate_count)
        .map(|_| GateWires {
            fresh: take_array(&mut cursor),
            output: take_array(&mut cursor),
            chaff: take_array(&mut cursor),
        })
        .collect();
    let scratch = take_array::<1>(&mut cursor)[0];
    let scratch2 = take_array::<1>(&mut cursor)[0];
    let (decomp, persistent, temporary) = match mode {
        #[cfg(feature = "legacy-tools")]
        NonlinearGssMode::Nonlinear193 => (None, None, None),
        NonlinearGssMode::Nonlinear291 => (
            Some(take_array(&mut cursor)),
            Some(take_array(&mut cursor)),
            Some(take_array::<1>(&mut cursor)[0]),
        ),
    };
    let deltas = (0..logical_n)
        .map(|_| take_array::<1>(&mut cursor)[0])
        .collect();
    debug_assert_eq!(cursor, total);
    Ok(PhysicalLayout {
        values,
        gate_wires,
        shared: SharedWires {
            scratch,
            scratch2,
            decomp,
            persistent,
            temporary,
        },
        deltas,
        total,
    })
}

fn classify_source(source: &[XGate], logical_n: usize) -> Result<Vec<SourceOp>, String> {
    source
        .iter()
        .enumerate()
        .map(|(index, gate)| {
            let target = gate.target as usize;
            if target >= logical_n {
                return Err(format!(
                    "unsupported source gate {index}: target {target} is outside logical_n={logical_n}"
                ));
            }
            let mut ctrls: Vec<(usize, bool)> = gate
                .ctrls
                .iter()
                .map(|&(wire, polarity)| (wire as usize, polarity))
                .collect();
            ctrls.sort_unstable_by_key(|&(wire, polarity)| (wire, polarity));
            for pair in ctrls.windows(2) {
                if pair[0].0 == pair[1].0 {
                    return Err(format!(
                        "unsupported source gate {index}: duplicate control wire {}",
                        pair[0].0
                    ));
                }
            }
            if let Some(&(wire, _)) = ctrls
                .iter()
                .find(|&&(wire, _)| wire >= logical_n || wire == target)
            {
                return Err(format!(
                    "unsupported source gate {index}: control {wire} is outside the logical range or equals target {target}"
                ));
            }

            let shape_error = || {
                format!(
                    "unsupported source gate {index}: comp={} controls={ctrls:?}; expected r57, nab, positive AND, or positive copy",
                    gate.comp
                )
            };
            match (gate.comp, ctrls.as_slice()) {
                (true, [(negative, false), (positive, true)])
                | (true, [(positive, true), (negative, false)]) => Ok(SourceOp {
                    kind: TemplateOp::R57,
                    target,
                    a: Some(*negative),
                    b: *positive,
                }),
                (false, [(negative, false), (positive, true)])
                | (false, [(positive, true), (negative, false)]) => Ok(SourceOp {
                    kind: TemplateOp::Nab,
                    target,
                    a: Some(*negative),
                    b: *positive,
                }),
                (false, [(a, true), (b, true)]) => Ok(SourceOp {
                    kind: TemplateOp::And,
                    target,
                    a: Some(*a),
                    b: *b,
                }),
                (false, [(b, true)]) => Ok(SourceOp {
                    kind: TemplateOp::Copy,
                    target,
                    a: None,
                    b: *b,
                }),
                _ => Err(shape_error()),
            }
        })
        .collect()
}

fn expected_template_shape(mode: NonlinearGssMode, op: TemplateOp) -> (usize, usize, usize) {
    match (mode, op) {
        #[cfg(feature = "legacy-tools")]
        (NonlinearGssMode::Nonlinear193, TemplateOp::R57) => (44, 193, 4),
        #[cfg(feature = "legacy-tools")]
        (NonlinearGssMode::Nonlinear193, TemplateOp::Nab) => (44, 190, 4),
        #[cfg(feature = "legacy-tools")]
        (NonlinearGssMode::Nonlinear193, TemplateOp::And) => (44, 193, 4),
        #[cfg(feature = "legacy-tools")]
        (NonlinearGssMode::Nonlinear193, TemplateOp::Copy) => (34, 85, 3),
        (NonlinearGssMode::Nonlinear291, TemplateOp::R57) => (71, 291, 2),
        (NonlinearGssMode::Nonlinear291, TemplateOp::Nab) => (71, 288, 2),
        (NonlinearGssMode::Nonlinear291, TemplateOp::And) => (71, 291, 2),
        (NonlinearGssMode::Nonlinear291, TemplateOp::Copy) => (61, 127, 2),
    }
}

fn parse_bool(token: Option<&str>, context: &str) -> Result<bool, String> {
    match token {
        Some("0") => Ok(false),
        Some("1") => Ok(true),
        Some(other) => Err(format!("{context}: expected Boolean 0/1, got {other:?}")),
        None => Err(format!("{context}: missing Boolean field")),
    }
}

fn parse_usize(token: Option<&str>, context: &str) -> Result<usize, String> {
    token
        .ok_or_else(|| format!("{context}: missing integer field"))?
        .parse()
        .map_err(|_| format!("{context}: invalid unsigned integer"))
}

fn parse_template(text: &str, mode: NonlinearGssMode, op: TemplateOp) -> Result<Template, String> {
    let name = format!("{mode:?}_{} template", op.name());
    let (expected_wires, expected_gates, expected_max_fanin) = expected_template_shape(mode, op);
    let mut tokens = text.split_whitespace();
    if tokens.next() != Some("mpmct1") {
        return Err(format!("{name}: missing mpmct1 header"));
    }
    let num_wires = parse_usize(tokens.next(), &format!("{name} header wires"))?;
    let num_gates = parse_usize(tokens.next(), &format!("{name} header gates"))?;
    if (num_wires, num_gates) != (expected_wires, expected_gates) {
        return Err(format!(
            "{name}: canonical header mismatch: got wires/gates {num_wires}/{num_gates}, \
             expected {expected_wires}/{expected_gates}"
        ));
    }
    let mut gates = Vec::with_capacity(num_gates);
    for gate_index in 0..num_gates {
        let context = format!("{name} gate {gate_index}");
        let target = parse_usize(tokens.next(), &context)?;
        let comp = parse_bool(tokens.next(), &context)?;
        let fanin = parse_usize(tokens.next(), &context)?;
        if fanin > expected_max_fanin {
            return Err(format!(
                "{context}: fan-in {fanin} exceeds canonical maximum {expected_max_fanin}"
            ));
        }
        if target >= num_wires {
            return Err(format!(
                "{context}: target {target} is outside template width {num_wires}"
            ));
        }
        let mut ctrls = Vec::with_capacity(fanin);
        for _ in 0..fanin {
            let wire = parse_usize(tokens.next(), &context)?;
            let polarity = parse_bool(tokens.next(), &context)?;
            if wire >= num_wires || wire == target {
                return Err(format!(
                    "{context}: control {wire} is outside width or equals target {target}"
                ));
            }
            ctrls.push((wire, polarity));
        }
        ctrls.sort_unstable_by_key(|&(wire, polarity)| (wire, polarity));
        if ctrls.windows(2).any(|pair| pair[0].0 == pair[1].0) {
            return Err(format!("{context}: duplicate control wire"));
        }
        gates.push(TemplateGate {
            target,
            comp,
            ctrls,
        });
    }
    if let Some(extra) = tokens.next() {
        return Err(format!("{name}: trailing token {extra:?}"));
    }
    let actual_max_fanin = gates.iter().map(|gate| gate.ctrls.len()).max().unwrap_or(0);
    if actual_max_fanin != expected_max_fanin {
        return Err(format!(
            "{name}: canonical max-fan-in mismatch: got {actual_max_fanin}, \
             expected {expected_max_fanin}"
        ));
    }
    Ok(Template { num_wires, gates })
}

fn canonical_template(mode: NonlinearGssMode, op: TemplateOp) -> Result<&'static Template, String> {
    #[cfg(feature = "legacy-tools")]
    static T193_R57: OnceLock<Result<Template, String>> = OnceLock::new();
    #[cfg(feature = "legacy-tools")]
    static T193_NAB: OnceLock<Result<Template, String>> = OnceLock::new();
    #[cfg(feature = "legacy-tools")]
    static T193_AND: OnceLock<Result<Template, String>> = OnceLock::new();
    #[cfg(feature = "legacy-tools")]
    static T193_COPY: OnceLock<Result<Template, String>> = OnceLock::new();
    static T291_R57: OnceLock<Result<Template, String>> = OnceLock::new();
    static T291_NAB: OnceLock<Result<Template, String>> = OnceLock::new();
    static T291_AND: OnceLock<Result<Template, String>> = OnceLock::new();
    static T291_COPY: OnceLock<Result<Template, String>> = OnceLock::new();

    let (cell, text) = match (mode, op) {
        #[cfg(feature = "legacy-tools")]
        (NonlinearGssMode::Nonlinear193, TemplateOp::R57) => (&T193_R57, TEMPLATE_193_R57),
        #[cfg(feature = "legacy-tools")]
        (NonlinearGssMode::Nonlinear193, TemplateOp::Nab) => (&T193_NAB, TEMPLATE_193_NAB),
        #[cfg(feature = "legacy-tools")]
        (NonlinearGssMode::Nonlinear193, TemplateOp::And) => (&T193_AND, TEMPLATE_193_AND),
        #[cfg(feature = "legacy-tools")]
        (NonlinearGssMode::Nonlinear193, TemplateOp::Copy) => (&T193_COPY, TEMPLATE_193_COPY),
        (NonlinearGssMode::Nonlinear291, TemplateOp::R57) => (&T291_R57, TEMPLATE_291_R57),
        (NonlinearGssMode::Nonlinear291, TemplateOp::Nab) => (&T291_NAB, TEMPLATE_291_NAB),
        (NonlinearGssMode::Nonlinear291, TemplateOp::And) => (&T291_AND, TEMPLATE_291_AND),
        (NonlinearGssMode::Nonlinear291, TemplateOp::Copy) => (&T291_COPY, TEMPLATE_291_COPY),
    };
    cell.get_or_init(|| parse_template(text, mode, op))
        .as_ref()
        .map_err(Clone::clone)
}

fn map_block<const N: usize>(map: &mut [usize], local_start: usize, global: &[u16; N]) {
    for (offset, &wire) in global.iter().enumerate() {
        map[local_start + offset] = wire as usize;
    }
}

fn append_template(
    out: &mut Vec<XGate>,
    template: &Template,
    op: SourceOp,
    target: EncodedValue,
    a: Option<EncodedValue>,
    b: EncodedValue,
    wires: GateWires,
    shared: &SharedWires,
) -> Result<(), String> {
    let mut map = vec![usize::MAX; template.num_wires];
    map_block(&mut map, 0, &target.share1);
    map_block(&mut map, 5, &target.share2);
    map_block(&mut map, 10, &wires.fresh);
    let (output_start, scratch, scratch2, chaff_start, extra_start) = if op.kind.has_a() {
        let a = a.ok_or_else(|| format!("{} template is missing operand a", op.kind.name()))?;
        map_block(&mut map, 15, &a.share1);
        map_block(&mut map, 20, &a.share2);
        map_block(&mut map, 25, &b.share1);
        map_block(&mut map, 30, &b.share2);
        (35, 38, 39, 40, 44)
    } else {
        map_block(&mut map, 15, &b.share1);
        map_block(&mut map, 20, &b.share2);
        (25, 28, 29, 30, 34)
    };
    map_block(&mut map, output_start, &wires.output);
    map[scratch] = shared.scratch as usize;
    map[scratch2] = shared.scratch2 as usize;
    map_block(&mut map, chaff_start, &wires.chaff);
    if let (Some(decomp), Some(persistent), Some(temporary)) =
        (shared.decomp, shared.persistent, shared.temporary)
    {
        map_block(&mut map, extra_start, &decomp);
        map_block(&mut map, extra_start + 2, &persistent);
        map[extra_start + 26] = temporary as usize;
    }
    if let Some(local) = map.iter().position(|&wire| wire == usize::MAX) {
        return Err(format!(
            "{} template local wire {local} has no semantic mapping",
            op.kind.name()
        ));
    }

    out.reserve(template.gates.len());
    for gate in &template.gates {
        let mut ctrls: Lits = gate
            .ctrls
            .iter()
            .map(|&(wire, polarity)| (map[wire] as u16, polarity))
            .collect();
        sort_lits(&mut ctrls);
        out.push(XGate {
            target: map[gate.target] as u16,
            comp: gate.comp,
            ctrls,
        });
    }
    Ok(())
}

fn xor_e_into(target: u16, block: [u16; 5], out: &mut Vec<XGate>) {
    out.push(XGate::cnot(target, block[0]));
    out.push(XGate::cnot(target, block[1]));
    for (a, b) in [(2usize, 3usize), (3, 4), (2, 4)] {
        out.push(
            XGate::conj(target, [(block[a], true), (block[b], true)])
                .expect("E block and delta wires are distinct"),
        );
    }
}

fn emit_balanced_data_mask(target: u16, data_n: usize, rng: &mut impl Rng, out: &mut Vec<XGate>) {
    // raw_i XOR (raw_j AND raw_k), with i/j/k distinct. The independent
    // linear term makes the result balanced over uniform raw data.
    let i = rng.random_range(0..data_n);
    let j = loop {
        let candidate = rng.random_range(0..data_n);
        if candidate != i {
            break candidate;
        }
    };
    let k = loop {
        let candidate = rng.random_range(0..data_n);
        if candidate != i && candidate != j {
            break candidate;
        }
    };
    out.push(XGate::cnot(target, i as u16));
    out.push(
        XGate::conj(target, [(j as u16, true), (k as u16, true)])
            .expect("mask target is nondata and data controls are distinct"),
    );
}

fn checked_preblock_gate_counts(
    nondata: usize,
    slice_gate_count: usize,
    mode: NonlinearGssMode,
) -> Result<(usize, usize), String> {
    let minimum = nondata
        .checked_mul(SLICE_ZERO_CCNOT_GATES_PER_WIRE)
        .ok_or_else(|| "nonlinear GSS slice-preblock gate-count overflow".to_string())?;
    let requested = slice_gate_count.max(minimum);
    let maximum = nondata
        .checked_mul(MAX_SLICE_GATES_PER_NONDATA_WIRE)
        .ok_or_else(|| "nonlinear GSS slice-preblock resource-limit overflow".to_string())?;
    if requested > maximum {
        return Err(format!(
            "nonlinear GSS slice preblock requests {requested} logical gates for {nondata} \
             slice wires; the bounded limit is {maximum} \
             ({MAX_SLICE_GATES_PER_NONDATA_WIRE} per slice wire)"
        ));
    }

    let emitted = match mode {
        #[cfg(feature = "legacy-tools")]
        NonlinearGssMode::Nonlinear193 => requested,
        NonlinearGssMode::Nonlinear291 => {
            let cnots = requested / 3;
            let rest = requested - cnots;
            let quads = rest / 2;
            let ccnots = rest - quads;
            cnots
                .checked_add(ccnots)
                .and_then(|count| count.checked_add(quads.checked_mul(4)?))
                .ok_or_else(|| {
                    "nonlinear291 decomposed slice-preblock gate-count overflow".to_string()
                })?
        }
    };
    Ok((requested, emitted))
}

fn checked_body_gate_count(
    source_ops: &[SourceOp],
    logical_n: usize,
    mode: NonlinearGssMode,
) -> Result<usize, String> {
    let templates = source_ops.iter().try_fold(0usize, |count, op| {
        count
            .checked_add(expected_template_shape(mode, op.kind).1)
            .ok_or_else(|| "nonlinear GSS template gate-count overflow".to_string())
    })?;
    let logical = logical_n
        .checked_mul(INGRESS_GATES_PER_LOGICAL + EGRESS_GATES_PER_LOGICAL)
        .ok_or_else(|| "nonlinear GSS logical bookend gate-count overflow".to_string())?;
    let borrows = source_ops
        .len()
        .checked_mul(INGRESS_GATES_PER_SOURCE_GATE)
        .ok_or_else(|| "nonlinear GSS borrow-ingress gate-count overflow".to_string())?;
    logical
        .checked_add(borrows)
        .and_then(|count| count.checked_add(templates))
        .ok_or_else(|| "nonlinear GSS body gate-count overflow".to_string())
}

/// Validate the nonlinear adapter's complete wire and emitted-gate envelope.
///
/// The gate result is a conservative upper bound because heterogeneous copy
/// and `nab` templates are shorter than the longest template in each family.
/// Callers that create source artifacts should run this before sampling or
/// writing them; the adapter repeats it before classifying or allocating.
pub fn nonlinear_gss_resource_plan(
    logical_n: usize,
    gate_count: usize,
    slice_gate_count: usize,
    mode: NonlinearGssMode,
) -> Result<(usize, usize), String> {
    let total_wires = nonlinear_gss_wire_count(logical_n, gate_count, mode)?;
    let nondata = total_wires
        .checked_sub(logical_n)
        .ok_or_else(|| "nonlinear GSS nondata wire-count underflow".to_string())?;
    let (_, emitted_preblock) = checked_preblock_gate_counts(nondata, slice_gate_count, mode)?;
    let max_template = match mode {
        #[cfg(feature = "legacy-tools")]
        NonlinearGssMode::Nonlinear193 => 193usize,
        NonlinearGssMode::Nonlinear291 => 291usize,
    };
    let logical_bookends = logical_n
        .checked_mul(INGRESS_GATES_PER_LOGICAL + EGRESS_GATES_PER_LOGICAL)
        .ok_or_else(|| "nonlinear GSS logical bookend gate-count overflow".to_string())?;
    let per_source = INGRESS_GATES_PER_SOURCE_GATE
        .checked_add(max_template)
        .ok_or_else(|| "nonlinear GSS per-source gate-count overflow".to_string())?;
    let body_upper = gate_count
        .checked_mul(per_source)
        .and_then(|count| count.checked_add(logical_bookends))
        .ok_or_else(|| "nonlinear GSS body gate-count upper-bound overflow".to_string())?;
    let emitted_upper = emitted_preblock
        .checked_add(body_upper)
        .ok_or_else(|| "nonlinear GSS total emitted gate-count overflow".to_string())?;
    let vec_limit = (isize::MAX as usize) / std::mem::size_of::<XGate>().max(1);
    if emitted_upper > vec_limit {
        return Err(format!(
            "nonlinear GSS adapter may emit {emitted_upper} gates, beyond the Vec allocation \
             ceiling {vec_limit} for this platform"
        ));
    }
    Ok((total_wires, emitted_upper))
}

/// A fixed number of disjoint adjacent commuting-swap passes. Every accepted
/// swap is semantics-preserving, while the fixed pass count makes work linear
/// in the emitted circuit size instead of quadratic on long commuting runs.
fn bounded_commuting_reorder(gates: &mut [XGate], rng: &mut impl Rng) {
    if gates.len() < 2 {
        return;
    }
    for pass in 0..NONLINEAR_SHUFFLE_PASSES {
        let mut index = (pass + rng.random_range(0..2)) & 1;
        while index + 1 < gates.len() {
            if rng.random_bool(0.5) && !XGate::collides(&gates[index], &gates[index + 1]) {
                gates.swap(index, index + 1);
            }
            index += 2;
        }
    }
}

/// Gadgetize the supported heterogeneous GSS source shapes with a canonical
/// nonlinear E-gadget body.
///
/// Supported source gates are r57 (complemented, one negative and one positive
/// control), `!a & b`, positive AND, and positive copy.  All targets and
/// controls must name distinct wires below `logical_n`.  Every source gate gets
/// unique five-wire resharing, three clean output, and four chaff regions;
/// restored scratch and (for 291) decomposition/cache wires are shared.
/// `data_n` names the stable raw prefix used to derive balanced ingress masks;
/// GSS passes the original source width while `logical_n` is the sandwich's
/// doubled width.  Correctness is guaranteed when all wires at and above
/// `logical_n` start at zero.
///
/// The exact body gate counts are 193/190/193/85 for r57/nab/and/copy in
/// `Nonlinear193`, and 291/288/291/127 in `Nonlinear291`.  The returned circuit
/// additionally contains ingress, egress, and slice-preblock gates.
pub fn gadgetize_xgates_nonlinear_gss(
    source: &[XGate],
    logical_n: usize,
    data_n: usize,
    slice_gate_count: usize,
    mode: NonlinearGssMode,
    rng: &mut impl Rng,
) -> Result<CnotCircuit, String> {
    if logical_n < 3 {
        return Err(format!(
            "nonlinear GSS adapter requires logical_n >= 3, got {logical_n}"
        ));
    }
    if !(3..=logical_n).contains(&data_n) {
        return Err(format!(
            "nonlinear GSS adapter requires 3 <= data_n <= logical_n; got data_n={data_n}, logical_n={logical_n}"
        ));
    }
    // Bound the source-dependent layout before `classify_source` allocates its
    // parallel operation vector or any physical-wire layout is constructed.
    let (planned_total, planned_output_upper) =
        nonlinear_gss_resource_plan(logical_n, source.len(), slice_gate_count, mode)?;
    let source_ops = classify_source(source, logical_n)?;
    let layout = build_layout(logical_n, source.len(), mode)?;
    debug_assert_eq!(layout.total, planned_total);

    // Parse every used template before constructing output, so a canonical
    // artifact mismatch fails without returning a partially built circuit.
    for op in &source_ops {
        canonical_template(mode, op.kind)?;
    }

    let nondata = layout.total - logical_n;
    // The nonlinear layout has far more slice wires than the product family.
    // Preserve the existing ten-probes-per-slice-wire budget instead of
    // collapsing to one read per auxiliary, which is unstable at small widths.
    let (preblock_gates, emitted_preblock_gates) =
        checked_preblock_gate_counts(nondata, slice_gate_count, mode)?;
    let planned_body_gates = checked_body_gate_count(&source_ops, logical_n, mode)?;
    let planned_output_gates = emitted_preblock_gates
        .checked_add(planned_body_gates)
        .ok_or_else(|| "nonlinear GSS total emitted gate-count overflow".to_string())?;
    debug_assert!(planned_output_gates <= planned_output_upper);
    let mut circuit = try_nonlinear_slice_zero_preblock_dims(
        logical_n,
        nondata,
        preblock_gates,
        mode == NonlinearGssMode::Nonlinear291,
        layout.shared.scratch,
        layout.shared.scratch2,
        rng,
    )
    .map_err(|error| format!("nonlinear GSS slice preblock failed: {error}"))?;
    if circuit.gates.len() != emitted_preblock_gates {
        return Err(format!(
            "nonlinear GSS slice-preblock planner drift: planned {emitted_preblock_gates} \
             emitted gates, built {}",
            circuit.gates.len()
        ));
    }
    let mut body = Vec::new();
    body.try_reserve_exact(planned_body_gates)
        .map_err(|error| format!("cannot reserve nonlinear GSS body: {error}"))?;

    // Reversible seeded ingress. Free carrier coordinates and every strict
    // per-gate borrow receive balanced functions of the stable raw data
    // prefix. Output, scratch, decomposition, and delta wires remain clean.
    // Finally solve share-one c0 so E(S1)^E(S2) is exactly the raw logical bit.
    for (raw, value) in layout.values.iter().enumerate() {
        for &wire in value.share1[1..].iter().chain(value.share2.iter()) {
            emit_balanced_data_mask(wire, data_n, rng, &mut body);
        }
        let c0 = value.share1[0];
        body.push(XGate::cnot(c0, raw as u16));
        body.push(XGate::cnot(c0, value.share1[1]));
        for (a, b) in [(2usize, 3usize), (3, 4), (2, 4)] {
            body.push(
                XGate::conj(c0, [(value.share1[a], true), (value.share1[b], true)])
                    .expect("share-one lanes are distinct"),
            );
        }
        xor_e_into(c0, value.share2, &mut body);
    }
    for wires in &layout.gate_wires {
        for &wire in wires.fresh.iter().chain(wires.chaff.iter()) {
            emit_balanced_data_mask(wire, data_n, rng, &mut body);
        }
    }

    let mut current = layout.values.clone();
    for (index, op) in source_ops.iter().copied().enumerate() {
        let target = current[op.target];
        let a = op.a.map(|wire| current[wire]);
        let b = current[op.b];
        let template = canonical_template(mode, op.kind)?;
        append_template(
            &mut body,
            template,
            op,
            target,
            a,
            b,
            layout.gate_wires[index],
            &layout.shared,
        )?;
        let output = layout.gate_wires[index].output;
        current[op.target] = EncodedValue {
            share1: layout.gate_wires[index].fresh,
            share2: [
                target.share2[0],
                target.share2[1],
                output[0],
                output[1],
                output[2],
            ],
        };
    }

    // Clean-delta egress.  Starting from delta=0:
    //   delta ^= raw ^ E(S1) ^ E(S2); raw ^= delta,
    // hence raw becomes the final logical value while delta may remain junk.
    for raw in 0..logical_n {
        let delta = layout.deltas[raw];
        body.push(XGate::cnot(delta, raw as u16));
        xor_e_into(delta, current[raw].share1, &mut body);
        xor_e_into(delta, current[raw].share2, &mut body);
        body.push(XGate::cnot(raw as u16, delta));
    }

    if body.len() != planned_body_gates {
        return Err(format!(
            "nonlinear GSS body planner drift: planned {planned_body_gates} gates, built {}",
            body.len()
        ));
    }
    circuit
        .gates
        .try_reserve_exact(body.len())
        .map_err(|error| format!("cannot reserve complete nonlinear GSS circuit: {error}"))?;
    circuit.gates.extend(body);
    debug_assert_eq!(circuit.gates.len(), planned_output_gates);
    circuit.num_wires = layout.total;
    // Mix locally across the preblock/bookend/body seams with bounded work.
    // Dependencies keep a preblock read before any write of its slice control,
    // preserving the zero-slice contract exactly.
    bounded_commuting_reorder(&mut circuit.gates, rng);
    Ok(circuit)
}

/// Supported nonlinear291 constructor with the mode fixed explicitly. Logical
/// data lives on `0..logical_n`; every higher input wire must start at zero.
pub fn preprocess_nonlinear291(
    source: &[XGate],
    logical_n: usize,
    data_n: usize,
    slice_gate_count: usize,
    rng: &mut impl Rng,
) -> Result<CnotCircuit, String> {
    gadgetize_xgates_nonlinear_gss(
        source,
        logical_n,
        data_n,
        slice_gate_count,
        NonlinearGssMode::Nonlinear291,
        rng,
    )
}

#[cfg(test)]
#[path = "../../../tests/stages/preprocessing/nonlinear291.rs"]
mod tests;
