#!/usr/bin/env python3
"""Try random partial input assignments of a DIMACS problem with external Kissat.

A satisfiable cube is a witness for the original formula. Failure to find one
is inconclusive: the sampled cubes do not cover the full input space.
"""

import argparse
import random
import re
import subprocess
import sys
import shutil
from pathlib import Path


def read_dimacs(path: Path):
    text = path.read_text()
    match = re.search(r"^p cnf (\d+) (\d+)\s*$", text, re.MULTILINE)
    if not match:
        raise SystemExit(f"missing DIMACS header in {path}")
    return text, int(match.group(1)), int(match.group(2)), match


def solver_status(output: str, returncode: int) -> str:
    statuses = {line.strip() for line in output.splitlines() if line.startswith("s ")}
    if statuses == {"s SATISFIABLE"} and returncode == 10:
        return "SAT"
    if statuses == {"s UNSATISFIABLE"} and returncode == 20:
        return "UNSAT"
    if returncode == 0 and (not statuses or statuses == {"s UNKNOWN"}):
        return "UNKNOWN"
    return "ERROR"


def write_cube_cnf(base_text: str, vars_count: int, clauses_count: int, units, out: Path):
    header = f"p cnf {vars_count} {clauses_count + len(units)}"
    text = re.sub(r"^p cnf \d+ \d+\s*$", header, base_text, count=1, flags=re.MULTILINE)
    with out.open("w") as f:
        f.write(text)
        if not text.endswith("\n"):
            f.write("\n")
        for lit in units:
            f.write(f"{lit} 0\n")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-cnf", required=True, type=Path, help="DIMACS formula generated by zero_slice_to_cnf")
    parser.add_argument("--out-dir", required=True, type=Path, help="new output directory for cube formulas and solver logs")
    parser.add_argument("--kissat", default="kissat", help="Kissat executable path or name on PATH")
    parser.add_argument("--cubes", type=int, default=8, help="number of independently sampled cubes")
    parser.add_argument("--fixed-bits", type=int, default=1, help="number of input variables fixed in each cube")
    parser.add_argument("--var-start", type=int, default=1)
    parser.add_argument("--var-count", type=int, required=True, help="logical input width; initial variables start at var-start")
    parser.add_argument("--center-hex", default="", help="fix chosen bits to this input value instead of random values")
    parser.add_argument("--seconds", type=int, default=45, help="Kissat time limit per cube")
    parser.add_argument("--seed", type=int, default=1)
    args = parser.parse_args(argv)
    if args.cubes <= 0 or args.seconds <= 0 or args.var_count <= 0:
        parser.error("cubes, seconds, and var-count must be positive")
    if not 0 <= args.fixed_bits <= args.var_count:
        parser.error("fixed-bits must lie between 0 and var-count")
    solver = shutil.which(args.kissat)
    if solver is None:
        parser.error(f"Kissat executable not found: {args.kissat}")
    base_text, vars_count, clauses_count, _ = read_dimacs(args.base_cnf)
    if args.var_start < 1 or args.var_start + args.var_count - 1 > vars_count:
        parser.error("selected input variables exceed the DIMACS variable range")
    rng = random.Random(args.seed)
    free_vars = list(range(args.var_start, args.var_start + args.var_count))
    try:
        center = int(args.center_hex, 16) if args.center_hex else None
    except ValueError:
        parser.error("center-hex must be hexadecimal")
    if center is not None and not 0 <= center < 1 << args.var_count:
        parser.error("center-hex exceeds var-count bits")
    args.out_dir.mkdir(parents=True, exist_ok=False)

    for idx in range(args.cubes):
        chosen = sorted(rng.sample(free_vars, args.fixed_bits))
        units = []
        for var in chosen:
            if center is None:
                bit = rng.getrandbits(1)
            else:
                bit = (center >> (var - args.var_start)) & 1
            units.append(var if bit else -var)
        cnf = args.out_dir / f"input_cube_{idx:03d}.cnf"
        out = args.out_dir / f"input_cube_{idx:03d}.out"
        err = args.out_dir / f"input_cube_{idx:03d}.err"
        write_cube_cnf(base_text, vars_count, clauses_count, units, cnf)
        cmd = [
            solver,
            "--sat",
            f"--time={args.seconds}",
            f"--seed={args.seed + idx}",
            str(cnf),
        ]
        with out.open("w") as so, err.open("w") as se:
            proc = subprocess.run(cmd, stdout=so, stderr=se)
        output = out.read_text(errors="replace")
        status = solver_status(output, proc.returncode)
        print(
            f"cube {idx} status={status} return={proc.returncode} fixed={args.fixed_bits} out={out}",
            flush=True,
        )
        if status == "SAT":
            print(str(out))
            return 0
        if status == "ERROR":
            print(f"solver failed; see {err}", file=sys.stderr)
            return 2
    print("INCONCLUSIVE: no sampled cube produced a satisfying model; this does not prove the original formula UNSAT")
    return 1


if __name__ == "__main__":
    sys.exit(main())
